name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.7"

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze
        continue-on-error: true
        run: flutter analyze

      - name: Run tests
        continue-on-error: true
        run: flutter test

      - name: Build APK
        run: |
          flutter build apk --release \
            --dart-define=API_URL=${{ secrets.API_URL }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
